spring:
  cloud:
    azure:
      storage:
        table:
          account-name: proiectdatc
          account-key: 4rAGkkF2JqgpqQK9kguKr9K/uxPLG+vQmJgGsxDTB/DlWX1SEGxDFVSgqqInzcpoj+i/1TXaC8ad+ASt4i6FKw==
          endpoint: https://proiectdatc.table.core.windows.net